name: Check GitHub Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-runner:
    runs-on: windows-latest
    steps:
      - name: Check Runner Availability
        run: |
          echo "Checking GitHub Runner availability..."
          systeminfo

      - name: Check Disk Space
        run: |
          echo "Checking available disk space..."
          wmic logicaldisk get size,freespace,caption

      - name: Check Rate Limit
        run: |
          echo "Checking GitHub API rate limit..."
          curl -s https://api.github.com/rate_limit | jq .rate
